
#define SOUND_SHORTSWORDATTACK	0
#define SOUND_LONGSWORDATTACK	1
#define SOUND_BOWAIMING			2
#define SOUND_BOWSHOOT			3
#define SOUND_AXEATTACK			4
#define SOUND_MENDAMAGE			5
#define SOUND_WOMENDAMAGE		6
#define SOUND_WALKLAND			7
#define SOUND_WALKGLASS			8
#define SOUND_RUNLAND			9
#define SOUND_RUNGLASS			10
#define SOUND_MENDYING			11
#define SOUND_WOMENDYING		12
#define SOUND_BAREHANDHIT		13
#define SOUND_SWORDHIT			14
#define SOUND_MACEHIT			15
#define SOUND_ARROWHIT			16


