newPRWelcomeComment: >
  Thanks for opening this pull request! Since this is your first pull request, in order for your PR to be accepted, you will need to submit a [Developer's Certificate of Origin](https://github.com/Helbreath/client/wiki/Developer's-Certificate-of-Origin).
