
#define DYNAMICOBJECT_FIRE			1
#define DYNAMICOBJECT_FISH			2
#define DYNAMICOBJECT_FISHOBJECT	3
#define DYNAMICOBJECT_MINERAL1		4
#define DYNAMICOBJECT_MINERAL2		5
#define DYNAMICOBJECT_ARESDENFLAG	6
#define DYNAMICOBJECT_ELVINEFLAG		7
#define DYNAMICOBJECT_ICESTORM		8
#define DYNAMICOBJECT_SPIKE			9
#define DYNAMICOBJECT_PCLOUD_BEGIN	10
#define DYNAMICOBJECT_PCLOUD_LOOP	11
#define DYNAMICOBJECT_PCLOUD_END	12
#define DYNAMICOBJECT_FIRE2			13
#define DYNAMICOBJECT_FIRE3			14 // Snoopy, for FireBow
