
enum skillIndexes
{
	SKILL_MINING,			// 0
	SKILL_FISHING,			// 1
	SKILL_FARMING,			// 2
	SKILL_MAGICRES,			// 3
	SKILL_MAGIC,			// 4
	SKILL_HANDATTACK,		// 5
	SKILL_ARCHERY,			// 6
	SKILL_SHORTSWORD,		// 7
	SKILL_LONGSWORD,		// 8
	SKILL_FENCING,			// 9
	SKILL_AXE,				// 10
	SKILL_SHIELD,			// 11
	SKILL_ALCHEMY,			// 12
	SKILL_MANUFACTURING,	// 13
	SKILL_HAMMER,			// 14
	SKILL_15,			    // 15	
	SKILL_CRAFTING,			// 16	
	SKILL_17,				
	SKILL_18,
	SKILL_PRETENDCORPSE,	// 19
	SKILL_20,
	SKILL_STAFF,			// 21
	SKILL_22,
	SKILL_POISONRES			// 23
};