//#define TOTALCHARACTERS		80	//100 <- original

#define TOTALCHARACTERS		120  // for CLEROTH - NEW MONSTERS
#define TOTALACTION			15

#define OBJECTSTOP			0
#define OBJECTMOVE			1
#define OBJECTRUN				2
#define OBJECTATTACK			3
#define OBJECTMAGIC			4
#define OBJECTGETITEM		5
#define OBJECTDAMAGE			6
#define OBJECTDAMAGEMOVE	7
#define OBJECTATTACKMOVE	8
#define OBJECTDYING			10			   
#define OBJECTNULLACTION	100
#define OBJECTDEAD			101


#define OBJECTMOVE_CONFIRM				1001
#define OBJECTMOVE_REJECT				1010
#define OBJECTMOTION_CONFIRM			1020
#define OBJECTMOTION_ATTACK_CONFIRM		1030
#define OBJECTMOTION_REJECT				1040


