// Magic.h: interface for the CMagic class.
//
//////////////////////////////////////////////////////////////////////

#if !defined(AFX_MAGIC_H__15121CC0_F3E3_11D2_9B6C_00001C7030A6__INCLUDED_)
#define AFX_MAGIC_H__15121CC0_F3E3_11D2_9B6C_00001C7030A6__INCLUDED_

#include <windows.h>

#if _MSC_VER >= 1000
#pragma once
#endif // _MSC_VER >= 1000

enum magicTypes{
	MAGICTYPE_NONE,
	MAGICTYPE_DAMAGE_SPOT,
	MAGICTYPE_HPUP_SPOT,
	MAGICTYPE_DAMAGE_AREA,
	MAGICTYPE_SPDOWN_SPOT,	// unused
	MAGICTYPE_SPDOWN_AREA,
	MAGICTYPE_SPUP_SPOT,		// unused
	MAGICTYPE_SPUP_AREA,
	MAGICTYPE_TELEPORT,
	MAGICTYPE_SUMMON,
	MAGICTYPE_CREATE,
	MAGICTYPE_PROTECT,
	MAGICTYPE_HOLDOBJECT,
	MAGICTYPE_INVISIBILITY,
	MAGICTYPE_CREATE_DYNAMIC,
	MAGICTYPE_POSSESSION,
	MAGICTYPE_CONFUSE,
	MAGICTYPE_POISON,
	MAGICTYPE_BERSERK,
	MAGICTYPE_DAMAGE_LINEAR,
	MAGICTYPE_POLYMORPH,
	MAGICTYPE_DAMAGE_AREA_NOSPOT,
	MAGICTYPE_TREMOR,
	MAGICTYPE_ICE,
	MAGICTYPE_DAMAGE_SPOT_SPDOWN,		// no spells
	MAGICTYPE_DAMAGE_AREA_NOSPOT_SPDOWN,

	MAGICTYPE_DAMAGE_AREA_ARMOR_BREAK,
	MAGICTYPE_ICE_LINEAR,

	MAGICTYPE_CANCELLATION,
	MAGICTYPE_INHIBITION,	
	MAGICTYPE_DAMAGE_LINEAR_SPDOWN,
	MAGICTYPE_SCAN,
	MAGICTYPE_RESURRECTION,
	MAGICTYPE_DAMAGE_AREA_MOVE
};

enum magicChldProtect{
	MAGICPROTECT_PFA =		1,
	MAGICPROTECT_PFM =		2,
	MAGICPROTECT_AMP =		5,
	MAGICPROTECT_DS =		3,
	MAGICPROTECT_GDS =		4
};

class CMagic  
{
public:
	CMagic();
	virtual ~CMagic();
	char m_cName[31];
	int  m_sValue1, m_sValue2, m_sValue3;
	// CLEROTH
	int m_sValue4;
	bool m_bIsVisible;
};

#endif // !defined(AFX_MAGIC_H__15121CC0_F3E3_11D2_9B6C_00001C7030A6__INCLUDED_)
