
enum skillIndexes
{
    SKILL_MINING,
    SKILL_FISHING,
    SKILL_FARMING,
    SKILL_MAGICRES,
    SKILL_MAGIC,
    SKILL_HANDATTACK,
    SKILL_ARCHERY,
    SKILL_SHORTSWORD,
    SKILL_LONGSWORD,
    SKILL_FENCING,
    SKILL_AXE,
    SKILL_SHIELD,
    SKILL_ALCHEMY,
    SKILL_MANUFACTURING,
    SKILL_HAMMER,
    SKILL_15,
    SKILL_CRAFTING,
    SKILL_17,
    SKILL_18,
    SKILL_PRETENDCORPSE,
    SKILL_20,
    SKILL_STAFF,
    SKILL_22,
    SKILL_POISONRES
};