#ifndef ACTIONID_H
#define ACTIONID_H

#include "..\..\shared\netmessages.h"

#define TOTALCHARACTERS		120
#define TOTALACTION			15

#define OBJECTSTOP			0
#define OBJECTMOVE			1
#define OBJECTRUN				2
#define OBJECTATTACK			3
#define OBJECTMAGIC			4
#define OBJECTGETITEM		5
#define OBJECTDAMAGE			6
#define OBJECTDAMAGEMOVE	7
#define OBJECTATTACKMOVE	8
#define OBJECTDYING			10			   
#define OBJECTNULLACTION	100
#define OBJECTDEAD			101

#define OBJECTMOVE_CONFIRM				1001
#define OBJECTMOVE_REJECT				1010
#define OBJECTMOTION_CONFIRM			1020
#define OBJECTMOTION_ATTACK_CONFIRM		1030
#define OBJECTMOTION_REJECT				1040

static const char motion_to_actionid[MSGID_MOTION_MAX] =
{
	OBJECTSTOP, OBJECTMOVE, OBJECTRUN, OBJECTATTACK, OBJECTMAGIC, OBJECTGETITEM, OBJECTDAMAGE,
	OBJECTDAMAGEMOVE, OBJECTATTACKMOVE, OBJECTDYING, OBJECTNULLACTION, OBJECTNULLACTION, OBJECTNULLACTION
};

#define GET_MOTION_ACTIONID(x)	( motion_to_actionid[x & ~MSGIDTYPE_MOTION] )

#endif
